language: cpp

addons:
  apt:
    sources:
    packages:
      - cmake
      - cmake-data
      - libpoco-dev

compiler:
  - clang
  - gcc

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake .. -DENABLE_MAKE_TEST=ON

script:
  - cmake --build . -- -j${JOBS}
  - ctest --output-on-failure -j${JOBS}
